version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./blog:/var/www/html/blog:cached
      - ./conf.d:/etc/nginx/conf.d:cached
      - nginx:/var/log/nginx:cached
    restart: always
    networks:
      - webnet
  php:
    image: lince/php:7-fpm
    volumes:
      - ./blog:/var/www/html/blog:cached
    restart: always
    networks:
      - webnet
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
     - mysql:/var/lib/mysql:cached
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=zxcvbnm
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=0
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data:cached
    command: redis-server --appendonly yes
    restart: always
    networks:
      - webnet
  # node:
  #   image: node:alpine
  #   working_dir: /blog
  #   volumes:
  #     - ./blog:/blog
  #   restart: always
  #   command: "npm start"
  #   networks:
  #     - webnet
networks:
  webnet:
volumes:
  mysql:
  redis:
  nginx: